# Generated by Django 5.0.4 on 2024-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
