# Generated by Django 5.0.4 on 2024-05-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='No_Name', max_length=250),
        ),
    ]
